numpy arrays

Question 1: Create a NumPy array with 5 elements initialized with zeros.

Question 2: Create a NumPy array with 3 rows and 4 columns initialized with ones.

Question 3: Create a 1D NumPy array containing numbers from 1 to 10.

Question 4: Create a 2D NumPy array with dimensions 3x3 containing numbers from 1 to 9.

Question 5: Create a 3D NumPy array with dimensions 2x3x4 containing random integers between 0 and 9.

Question 6: Create a NumPy array from a list containing elements [1, 2, 3, 4, 5].

Question 7: Convert a tuple (6, 7, 8, 9, 10) into a NumPy array.

Question 8: Create a NumPy array with shape (4, 2) containing numbers from 0 to 7.

Question 9: Create a 3D NumPy array with shape (2, 3, 4) initialized with zeros.

Question 10: Create a 2D NumPy array with shape (3, 3) containing random floating-point numbers between 0 and 1.

Question 11: Create a NumPy array with shape (5,) containing numbers from 10 to 50, incrementing by 5.

Question 12: Create a NumPy array with shape (2, 5) containing numbers from -2 to 7.

Question 13: Create a 1D NumPy array with shape (10,) containing numbers from 100 to 109, and change its data type to float.

Question 14: Create a 2D NumPy array with shape (3, 4) initialized with ones, and then change its data type to int.

Question 15: Create a 3D NumPy array with shape (2, 2, 3) initialized with specified numbers [[1, 2, 3], [4, 5, 6]], and [[7, 8, 9], [10, 11, 12]].

Question 1: Create a NumPy array with 5 elements initialized with zeros.

In [1]:
import numpy as np

In [6]:
a = np.zeros((3,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]

Question 2: Create a NumPy array with 3 rows and 4 columns initialized with ones.

In [7]:
b = np.ones((3,4), dtype=int)
print(b)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Question 3: Create a 1D NumPy array containing numbers from 1 to 10.

In [12]:
c = np.arange(1,11)
print(c)

[ 1  2  3  4  5  6  7  8  9 10]

Question 4: Create a 2D NumPy array with dimensions 3x3 containing numbers from 1 to 9.

In [13]:
d = np.random.randint(1,10,size=(3,3))
print(d)

[[2 9 4]
 [4 1 3]
 [2 8 6]]

Question 5: Create a 3D NumPy array with dimensions 2x3x4 containing random integers between 0 and 9.

In [14]:
e = np.random.randint(0,10,size=(2,3,4))
print(e)

[[[1 3 9 9]
  [8 4 1 9]
  [1 2 1 1]]

 [[7 4 2 7]
  [2 3 5 0]
  [2 9 3 3]]]

Question 6: Create a NumPy array from a list containing elements [1, 2, 3, 4, 5].

In [21]:
lis = [1, 2, 3, 4, 5]
f = np.array(lis)
print(f)

[1 2 3 4 5]

Question 7: Convert a tuple (6, 7, 8, 9, 10) into a NumPy array.

In [22]:
tp = (6, 7, 8, 9, 10)
g = np.array(tp)
print(g)

[ 6  7  8  9 10]

Question 8: Create a NumPy array with shape (4, 2) containing numbers from 0 to 7.

In [26]:
h = np.random.randint(0,8, size=(4,2))
print(h)

[[4 4]
 [4 1]
 [6 5]
 [6 4]]

Question 9: Create a 3D NumPy array with shape (2, 3, 4) initialized with zeros.

In [27]:
i = np.zeros((2,3,4), dtype=int)
print(i)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]

Question 10: Create a 2D NumPy array with shape (3, 3) containing random floating-point numbers between 0 and 1.

In [28]:
j = np.random.random((3,3))
print(j)

[[0.22479604 0.7119824  0.50386804]
 [0.05007621 0.26230158 0.48867673]
 [0.17255994 0.7655896  0.16664569]]

Question 11: Create a NumPy array with shape (5,) containing numbers from 10 to 50, incrementing by 5.

In [29]:
k = np.arange(10,35,5)
print(k)

[10 15 20 25 30]

Question 12: Create a NumPy array with shape (2, 5) containing numbers from -2 to 7.

In [31]:
l = np.random.randint(-2,8, size=(2,5))
print(l)

[[ 2  5 -1  7  4]
 [-2  7  4  7 -1]]

Question 13: Create a 1D NumPy array with shape (10,) containing numbers from 100 to 109, and change its data type to float.

In [37]:
m = np.arange(100,109)
m
n=m.astype('float64')
print(n)

[100. 101. 102. 103. 104. 105. 106. 107. 108.]

Question 14: Create a 2D NumPy array with shape (3, 4) initialized with ones, and then change its data type to int.

In [39]:
n = np.ones((3,4))
o = n.astype('int')
print(o)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Question 15: Create a 3D NumPy array with shape (2, 2, 3) initialized with specified numbers [[1, 2, 3], [4, 5, 6]], and [[7, 8, 9], [10, 11, 12]].

In [43]:
p = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])
print("Shape of array: ",p.shape)
print(p)

Shape of array:  (2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]